import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Bookly | Appointment Booking",
    description: "Generated by create next app",
};

export default function BusinessLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return <>{children}</>;
}
